CREATE TABLE IF NOT EXISTS buecher (
    Nummer INTEGER PRIMARY KEY AUTOINCREMENT,
    Autor VARCHAR(100) NOT NULL,
    Titel VARCHAR(100) NOT NULL,
    Genre VARCHAR(100),
    Format VARCHAR(100),
    Verlag VARCHAR(100),
    Seiten INTEGER,
    Laenge VARCHAR(10),
    ISBN VARCHAR(15),
    Jahr INTEGER,
    Preis FLOAT,
    Standort VARCHAR(100),
    Inhaltsangabe VARCHAR(2500),
    Bemerkungen VARCHAR(2500),
    Subtitel VARCHAR(100),
    SubgenreSachbuchRatgeber VARCHAR(100),
    SubgenreRatgeber VARCHAR(100),
    Auflage INTEGER,
    Schlagw VARCHAR(100),
    Bild VARCHAR(250)
);
